insert into authors (id, first_name, last_name) values (1, 'Xaviera', 'Jankowski');
insert into authors (id, first_name, last_name) values (2, 'Marillin', 'Goldine');
insert into authors (id, first_name, last_name) values (3, 'Caril', 'Erni');
insert into authors (id, first_name, last_name) values (4, 'Celine', 'Winterborne');
insert into authors (id, first_name, last_name) values (5, 'Darby', 'Jodkowski');
insert into authors (id, first_name, last_name) values (6, 'Lesli', 'Tregenza');
insert into authors (id, first_name, last_name) values (7, 'Orv', 'Clethro');
insert into authors (id, first_name, last_name) values (8, 'Kyle', 'Kusick');
insert into authors (id, first_name, last_name) values (9, 'Alden', 'Seer');
insert into authors (id, first_name, last_name) values (10, 'Blythe', 'Ralton');
insert into authors (id, first_name, last_name) values (11, 'Eyde', 'Saffen');
insert into authors (id, first_name, last_name) values (12, 'Binnie', 'Pattrick');
insert into authors (id, first_name, last_name) values (13, 'Lucretia', 'Daly');
insert into authors (id, first_name, last_name) values (14, 'Ruthi', 'Edinburgh');
insert into authors (id, first_name, last_name) values (15, 'Kora', 'Coo');
insert into authors (id, first_name, last_name) values (16, 'Trevor', 'Dix');
insert into authors (id, first_name, last_name) values (17, 'Hansiain', 'Whimpenny');
insert into authors (id, first_name, last_name) values (18, 'Perl', 'Royse');
insert into authors (id, first_name, last_name) values (19, 'Barret', 'Paeckmeyer');
insert into authors (id, first_name, last_name) values (20, 'Morna', 'Castellani');
insert into authors (id, first_name, last_name) values (21, 'Karlis', 'Humbee');


insert into books (id, price, price_old, title, author_id) values (1, 540, 3545, 'Aerified', 12);
insert into books (id, price, price_old, title, author_id) values (2, 725, 3687, 'Job', 1);
insert into books (id, price, price_old, title, author_id) values (3, 853, 2144, 'Flowdesk', 2);
insert into books (id, price, price_old, title, author_id) values (4, 1116, 1399, 'Bitwolf', 2);
insert into books (id, price, price_old, title, author_id) values (5, 1349, 1590, 'Span', 1);
insert into books (id, price, price_old, title, author_id) values (6, 1581, 1462, 'Y-find', 20);
insert into books (id, price, price_old, title, author_id) values (7, 1271, 3295, 'Andalax', 18);
insert into books (id, price, price_old, title, author_id) values (8, 1981, 1708, 'Zontrax', 14);
insert into books (id, price, price_old, title, author_id) values (9, 2157, 1920, 'Tres-Zap', 8);
insert into books (id, price, price_old, title, author_id) values (10, 894, 2305, 'Tresom', 2);
insert into books (id, price, price_old, title, author_id) values (11, 2349, 2426, 'Zontrax', 1);
insert into books (id, price, price_old, title, author_id) values (12, 1354, 1197, 'Matsoft', 14);
insert into books (id, price, price_old, title, author_id) values (13, 2793, 2923, 'Voltsillam', 19);
insert into books (id, price, price_old, title, author_id) values (14, 568, 2111, 'Vagram', 13);
insert into books (id, price, price_old, title, author_id) values (15, 2110, 1461, 'Gembucket', 4);
insert into books (id, price, price_old, title, author_id) values (16, 1187, 2237, 'Span', 12);
insert into books (id, price, price_old, title, author_id) values (17, 610, 3675, 'Home Ing', 19);
insert into books (id, price, price_old, title, author_id) values (18, 1960, 3352, 'Ronstring', 20);
insert into books (id, price, price_old, title, author_id) values (19, 2722, 2954, 'Matsoft', 12);
insert into books (id, price, price_old, title, author_id) values (20, 2637, 3379, 'It', 3);
insert into books (id, price, price_old, title, author_id) values (21, 1837, 1265, 'Trippledex', 5);